import { ToolDefinition } from '../types';

export const TOOLS_CONFIG: ToolDefinition[] = [
  {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    shortDesc: 'Convert JPG, PNG, WEBP images into an A4, Letter or custom PDF.',
    description: 'Upload multiple images, reorder, rotate, adjust margins and page sizes, then convert to high-quality PDF.',
    category: 'pdf',
    icon: 'FileImage',
    badge: 'Popular',
    featured: true,
    acceptedFileTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    shortDesc: 'Extract all or selected PDF pages into high-resolution JPG images.',
    description: 'Convert PDF pages into crisp images with customizable DPI and quality. Download single pages or ZIP package.',
    category: 'pdf',
    icon: 'FileText',
    badge: 'Popular',
    featured: true,
    acceptedFileTypes: ['application/pdf'],
  },
  {
    id: 'pdf-compress',
    title: 'PDF Compressor',
    shortDesc: 'Compress PDF size while retaining readability.',
    description: 'Reduce PDF file size by compressing embedded streams and images. Choose between Low, Medium, High compression.',
    category: 'pdf',
    icon: 'Minimize2',
    badge: 'High Savings',
    featured: true,
    acceptedFileTypes: ['application/pdf'],
  },
  {
    id: 'pdf-merge',
    title: 'PDF Merge',
    shortDesc: 'Combine multiple PDF files into a single unified document.',
    description: 'Merge 2 or more PDF documents in your preferred page order. Drag, reorder, and instantly generate one unified file.',
    category: 'pdf',
    icon: 'Layers',
    featured: true,
    acceptedFileTypes: ['application/pdf'],
  },
  {
    id: 'pdf-split',
    title: 'PDF Split',
    shortDesc: 'Extract individual pages or custom ranges from a PDF.',
    description: 'Split PDFs by range (e.g. 1-3, 4-7) or extract all pages as individual documents in a ZIP archive.',
    category: 'pdf',
    icon: 'Split',
    acceptedFileTypes: ['application/pdf'],
  },
  {
    id: 'pdf-rotate',
    title: 'PDF Rotate & Manage',
    shortDesc: 'Rotate, reorder, duplicate or delete individual PDF pages.',
    description: 'Visual thumbnail-based manager to rotate pages 90°/180°, reorder with drag, delete blank pages, or extract specific pages.',
    category: 'pdf',
    icon: 'RotateCw',
    acceptedFileTypes: ['application/pdf'],
  },
  {
    id: 'pdf-watermark',
    title: 'PDF Watermark',
    shortDesc: 'Stamp confidential, draft, or custom text/image watermarks.',
    description: 'Apply text or logo watermarks across every page of your PDF with customized opacity, rotation angle, font and color.',
    category: 'pdf',
    icon: 'Stamp',
    acceptedFileTypes: ['application/pdf'],
  },
  {
    id: 'pdf-protect',
    title: 'PDF Password Protect',
    shortDesc: 'Encrypt your PDF with a strong open password.',
    description: 'Secure sensitive documents with AES encryption so only recipients with your password can view the contents.',
    category: 'pdf',
    icon: 'Lock',
    acceptedFileTypes: ['application/pdf'],
  },
  {
    id: 'pdf-unlock',
    title: 'PDF Unlock',
    shortDesc: 'Remove password restrictions from authorized PDFs.',
    description: 'Decrypt and remove password security from your own PDF files by entering the current password.',
    category: 'pdf',
    icon: 'Unlock',
    acceptedFileTypes: ['application/pdf'],
  },
  {
    id: 'pdf-to-word',
    title: 'PDF to Word (DOCX)',
    shortDesc: 'Convert PDF documents into editable Word (.docx) format.',
    description: 'Extract layout, paragraphs, and headings from PDFs directly into an editable Microsoft Word DOCX document.',
    category: 'pdf',
    icon: 'FileCode2',
    badge: 'New',
    featured: true,
    acceptedFileTypes: ['application/pdf'],
  },
  {
    id: 'image-compress',
    title: 'Image Compressor',
    shortDesc: 'Compress JPG, PNG, WEBP with slider or exact target size.',
    description: 'Optimize image dimensions and byte size. Set quality (1-100) or target exact sizes like 20KB, 50KB, 100KB, 200KB.',
    category: 'image',
    icon: 'ImageDown',
    badge: 'Popular',
    featured: true,
    acceptedFileTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  {
    id: 'image-resize',
    title: 'Image Resize',
    shortDesc: 'Resize dimensions in px, mm, cm, or inches with aspect lock.',
    description: 'Fast pixel and physical unit resizing with aspect ratio locking, cropping, fitting, or filling.',
    category: 'image',
    icon: 'Scaling',
    acceptedFileTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  {
    id: 'custom-image-size',
    title: 'Custom Image Size',
    shortDesc: 'Set exact width and height with live canvas preview.',
    description: 'Precision dimension tool supporting px, mm, cm, and inches for custom print and digital submission specifications.',
    category: 'image',
    icon: 'Crop',
    acceptedFileTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  {
    id: 'target-file-size',
    title: 'Target File Size (KB/MB)',
    shortDesc: 'Iteratively compress files to meet strict portal limits.',
    description: 'Ideal for job applications & exams requiring exact limits like <20KB, <50KB, <100KB, <200KB without guessing.',
    category: 'image',
    icon: 'SlidersHorizontal',
    badge: 'Essential',
    acceptedFileTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  {
    id: 'passport-photo',
    title: 'Passport Photo Maker',
    shortDesc: 'Create 35x45mm or 2x2 inch passport photos on A4 print sheet.',
    description: 'Crop face, customize background color (white/blue/gray), and generate an A4 sheet with 8, 16, or 32 print-ready copies.',
    category: 'scanner',
    icon: 'UserSquare2',
    badge: 'Print Ready',
    featured: true,
    acceptedFileTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  {
    id: 'pan-card-scanner',
    title: 'PAN & ID Document Scanner',
    shortDesc: 'Format PAN, Aadhaar, Driving License, Passport to portal sizes.',
    description: '100% private in-browser camera or file upload. Crop, enhance, and export under 50KB/100KB/200KB as required by portals.',
    category: 'scanner',
    icon: 'CreditCard',
    badge: '100% Private',
    featured: true,
    acceptedFileTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
  },
  {
    id: 'document-scanner',
    title: 'Document Scanner',
    shortDesc: 'Mobile camera scan with B&W, Grayscale & Enhance filters.',
    description: 'Turn paper papers into crystal clear multi-page digital PDFs or JPGs with contrast enhancement and edge adjustment.',
    category: 'scanner',
    icon: 'ScanLine',
    badge: 'Mobile First',
    featured: true,
    acceptedFileTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  {
    id: 'pdf-letter-format',
    title: 'PDF Letter Formats',
    shortDesc: 'Ready-made templates for Leave, School, Bank, & Official letters.',
    description: 'Choose from 10+ standard Indian & international letter templates, fill details, preview live, and export to A4 PDF or DOCX.',
    category: 'letters',
    icon: 'ScrollText',
    badge: '10+ Templates',
    featured: true,
  },
  {
    id: 'letter-generator',
    title: 'Application & Letter Generator',
    shortDesc: 'Generate professional formal letters with standard formatting.',
    description: 'Custom formal letter builder with subject line, reference number, salutation, body paragraphs, and formal signature block.',
    category: 'letters',
    icon: 'PenTool',
  },
  {
    id: 'emi-calculator',
    title: 'EMI Calculator',
    shortDesc: 'Calculate Home, Car, & Personal loan EMIs with full schedule.',
    description: 'Accurate monthly EMI, total interest, principal breakdown, pie distribution, and month-by-month repayment schedule table.',
    category: 'utility',
    icon: 'Calculator',
    badge: 'Interactive',
    featured: true,
  },
];
